#!/usr/bin/env bash
# Auto-generated by docker/scripts/install-acestream.sh.
# Activates the bundled AceStream Python package and execs the engine.
set -euo pipefail

ACE_HOME="${ACE_HOME:-__ACE_HOME__}"
PYTHON_BIN="${ACESTREAM_PYTHON_BIN:-__PYTHON_BIN__}"
PY_MODULE="${ACESTREAM_PYTHON_MODULE:-__PY_MODULE__}"

export LD_LIBRARY_PATH="$ACE_HOME${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

PYPATH="$ACE_HOME:$ACE_HOME/site-packages"
shopt -s nullglob
for egg in "$ACE_HOME"/*.egg; do
    PYPATH="$egg:$PYPATH"
done
shopt -u nullglob
export PYTHONPATH="$PYPATH${PYTHONPATH:+:$PYTHONPATH}"

exec "$PYTHON_BIN" -m "$PY_MODULE" "$@"
