#!/usr/bin/env bash
set -euo pipefail

show_help() {
  cat <<'EOF'
Usage: verify_multiarch_manifest.sh [options]

Verify required architecture variants exist in either:
  1) a remote image manifest (via docker buildx imagetools inspect), or
  2) a local build-result metadata file generated by build_multiarch_images.sh.

Options:
  --image <ref>            Image reference to inspect remotely
  --result-file <path>     JSON result file from build_multiarch_images.sh
  --required <list>        Required platforms (default: linux/arm/v7,linux/arm64)
  --help                   Show this help

Examples:
  bash scripts/ci/verify_multiarch_manifest.sh --result-file multiarch-build-result.json
  bash scripts/ci/verify_multiarch_manifest.sh --image ghcr.io/acme/app:latest --required linux/arm/v7,linux/arm64
EOF
}

IMAGE_REF=""
RESULT_FILE=""
REQUIRED_PLATFORMS="linux/arm/v7,linux/arm64"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --image)
      IMAGE_REF="${2:-}"
      shift 2
      ;;
    --result-file)
      RESULT_FILE="${2:-}"
      shift 2
      ;;
    --required)
      REQUIRED_PLATFORMS="${2:-}"
      shift 2
      ;;
    --help|-h)
      show_help
      exit 0
      ;;
    *)
      echo "Unknown argument: $1"
      show_help
      exit 1
      ;;
  esac
done

if [[ -z "$IMAGE_REF" && -z "$RESULT_FILE" ]]; then
  echo "Provide either --image or --result-file."
  exit 1
fi

if [[ -n "$IMAGE_REF" && -n "$RESULT_FILE" ]]; then
  echo "Use only one source: --image or --result-file."
  exit 1
fi

tmp_json=""
cleanup() {
  if [[ -n "$tmp_json" && -f "$tmp_json" ]]; then
    rm -f "$tmp_json"
  fi
}
trap cleanup EXIT

if [[ -n "$IMAGE_REF" ]]; then
  if ! command -v docker >/dev/null 2>&1; then
    echo "docker is required for --image verification."
    exit 1
  fi
  tmp_json="$(mktemp)"
  docker buildx imagetools inspect "$IMAGE_REF" --raw >"$tmp_json"
  SOURCE_FILE="$tmp_json"
  SOURCE_TYPE="manifest"
else
  if [[ ! -f "$RESULT_FILE" ]]; then
    echo "Result file not found: $RESULT_FILE"
    exit 1
  fi
  SOURCE_FILE="$RESULT_FILE"
  SOURCE_TYPE="result"
fi

python3 - "$SOURCE_FILE" "$SOURCE_TYPE" "$REQUIRED_PLATFORMS" <<'PY'
import json
import sys
from typing import Set

source_file, source_type, required_csv = sys.argv[1:]
required = {item.strip() for item in required_csv.split(",") if item.strip()}

with open(source_file, "r", encoding="utf-8") as handle:
    payload = json.load(handle)

available: Set[str] = set()
if source_type == "manifest":
    manifests = payload.get("manifests", [])
    for manifest in manifests:
        platform = manifest.get("platform", {})
        os_name = platform.get("os")
        arch = platform.get("architecture")
        variant = platform.get("variant")
        if os_name and arch:
            platform_id = f"{os_name}/{arch}"
            if variant:
                platform_id = f"{platform_id}/{variant}"
            available.add(platform_id)
elif source_type == "result":
    platforms = payload.get("platforms", [])
    available.update(str(item).strip() for item in platforms if str(item).strip())
else:
    print(f"Unknown source type: {source_type}")
    sys.exit(2)

missing = sorted(required - available)
print("Required platforms:", ", ".join(sorted(required)))
print("Available platforms:", ", ".join(sorted(available)) if available else "(none)")

if missing:
    print("Missing platforms:", ", ".join(missing))
    sys.exit(1)

print("Manifest verification passed.")
PY

